# Generated by Django 4.2.23 on 2025-06-12 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("server", "Server"),
                            ("workstation", "Workstation"),
                            ("laptop", "Laptop"),
                            ("network", "Network Device"),
                            ("printer", "Printer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("mac_address", models.CharField(blank=True, max_length=17, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "discovered_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
