# Generated by Django 4.2.23 on 2025-06-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_asset_purchase_date_asset_replacement_due_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("retired", "Retired"),
                    ("faulty", "Faulty"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
