# Generated by Django 4.2.23 on 2025-06-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_alter_asset_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="network_range",
            field=models.CharField(
                blank=True, default="unknown", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("server", "Server"),
                    ("workstation", "Workstation"),
                    ("laptop", "Laptop"),
                    ("network", "Network Device"),
                    ("printer", "Printer"),
                ],
                default="workstation",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="location",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="mac_address",
            field=models.CharField(blank=True, default="", max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="manufacturer",
            field=models.CharField(blank=True, default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="asset",
            name="model",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="serial_number",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
