# Generated by Django 4.2.23 on 2025-06-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_asset_network_range_alter_asset_asset_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("network_range", models.CharField(max_length=50)),
                ("found_devices", models.IntegerField()),
            ],
        ),
    ]
