# Generated by Django 4.2.23 on 2025-06-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_riskscanresult_detectedservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskscanresult",
            name="vulnerabilities",
            field=models.TextField(default="[]"),
        ),
    ]
