# Generated by Django 4.2.23 on 2025-06-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_alter_riskscanresult_vulnerabilities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riskscanresult",
            name="vulnerabilities",
        ),
        migrations.AddField(
            model_name="riskscanresult",
            name="vulnerabilities_json",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
