# Generated by Django 4.2.23 on 2025-07-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_remove_riskscanresult_vulnerabilities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="scan_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discovered_assets",
                to="assets.scanlog",
            ),
        ),
    ]
